version: '3.7'
services:
  &app-service app: &app-service-template
    build:
      args:
        user: admin
        uid: 1000
      context: ./docker/app/
      dockerfile: Dockerfile
    image: dev.dvor24.local
    container_name: dev.dvor24.local-app
    user: root
    hostname: *app-service
    restart: always
    working_dir: /var/www/dev.dvor24.local
    volumes:
      - ./src:/var/www/dev.dvor24.local:rw
      - ./docker/app/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/app/etc/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/app/build:/var/www/build
    depends_on:
      - pgsql
    networks:
      # - app-network
      static-network:
        ipv4_address: 172.25.0.10

  &socket-service websocket:
    <<: *app-service-template
    container_name: dev.dvor24.local-socket
    restart: always
    hostname: *socket-service
    command: php /var/www/dev.dvor24.local/artisan websockets:serve
    ports:
      - 127.0.0.1:6001:6001
    networks:
      # - app-network
      static-network:
        ipv4_address: 172.25.0.9
      
  &scheduler-service scheduler:
    <<: *app-service-template
    container_name: dev.dvor24.local-scheduler
    restart: always
    hostname: *scheduler-service
    command: php /var/www/dev.dvor24.local/artisan schedule:work
    networks:
      # - app-network
      static-network:
        ipv4_address: 172.25.0.8

  &queue-service queue:
    <<: *app-service-template
    container_name: dev.dvor24.local-queue
    restart: always
    hostname: *queue-service
    command: php /var/www/dev.dvor24.local/artisan queue:work --tries=3
    networks:
      # - app-network
      static-network:
        ipv4_address: 172.25.0.5
    
  &nodename node:
    image: node:16.16-alpine
    container_name: dev.dvor24.local-node
    restart: on-failure
    hostname: *nodename
    volumes:
      - ./src:/var/www/dev.dvor24.local:rw
    working_dir: /var/www/dev.dvor24.local
    networks:
      # - app-network
      static-network:
        ipv4_address: 172.25.0.2

  &pgsqlname pgsql:
    image: postgres:13.7-alpine
    container_name: &pgsqlhost dev.dvor24.local-pgsql
    restart: always
    hostname: *pgsqlname
    environment: 
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dev
      POSTGRES_USER: dev
    volumes:
      - pg-data-admin:/var/lib/postgresql/data:rw
      - ./docker/pgsql/:/var/database
    networks:
      # - app-network
      static-network:
        ipv4_address: 172.25.0.3

  &phppgadmin phppgadmin:
    image: bitnami/phppgadmin:latest
    container_name: dev.dvor24.local-phppgadmin
    restart: always
    hostname: *pgsqlname
    ports:
      - 0.0.0.0:5050:8080
    environment: 
      DATABASE_ENABLE_EXTRA_LOGIN_SECURITY: 1
      DATABASE_HOST: *pgsqlhost
    volumes:
      - ./docker/pgsql/phppgadmin_data:/bitnami
    networks:
      # - app-network
      static-network:
        ipv4_address: 172.25.0.16

  &nginxname nginx:
    image: nginx:1.17-alpine
    container_name: dev.dvor24.local-nginx
    restart: always
    hostname: *nginxname
    ports:
      - 0.0.0.0:8080:80
      - 0.0.0.0:5173:5173
    volumes:
      - ./src:/var/www/dev.dvor24.local
      - ./docker/nginx:/etc/nginx/conf.d
      - ./logNginx:/var/log/nginx/
    networks:
      static-network:
        ipv4_address: 172.25.0.4
      # - app-network

networks:
  # app-network:
  #   driver: bridge
  static-network:
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  pg-data-admin:
    driver: local
  